language: objective-c
   
osx_image: xcode7.2

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '0.39.0'  

script: 
   xctool -workspace CoreDataFullStack.xcworkspace -scheme CoreDataFullStack build -sdk iphonesimulator
